db_uri: mongodb://192.168.230.2:27017/open5gs

udr:
  sbi:
    - dev: eth1
      advertise: 192.168.230.3
      port: 7780

nrf:
  sbi:
    - addr: 192.168.230.3
      port: 7777

parameter:
max:
pool:
time:
