#!/usr/bin/env python3
"""Victim-side metrics for the RA3 evaluation testbed.

The victim is the *target* of the traffic generated by the compromised UE. This
service reads, from the victim's own kernel and nginx, the observable symptoms
of being under load, and serves them as JSON. The test harness turns these into
the RA3 alert fields and, after RA3 acts, reads them again to decide whether the
alert was actually resolved.

    GET /metrics            all counters, one snapshot
    GET /health             {"status": "ok"}

Everything here is read-only measurement of this host. Nothing generates or
forwards traffic.
"""

from __future__ import annotations

import glob
import http.server
import json
import os
import re
import socket
import time

# TCP states from /proc/net/tcp[6] (hex). SYN_RECV = half-open connection.
TCP_SYN_RECV = "03"
TCP_ESTABLISHED = "01"
WATCH_PORTS = [int(p) for p in os.environ.get("WATCH_PORTS", "80,53,23,3306").split(",")]
NGINX_STATUS = os.environ.get("NGINX_STATUS", "http://127.0.0.1/nginx_status")


def _proc_tcp_counts() -> dict:
    """Count TCP sockets by state and by local port, from /proc/net/tcp[6]."""
    half_open = established = 0
    per_port_syn_recv: dict[int, int] = {}
    for path in ("/proc/net/tcp", "/proc/net/tcp6"):
        try:
            with open(path) as f:
                next(f)  # header
                for line in f:
                    cols = line.split()
                    if len(cols) < 4:
                        continue
                    local_port = int(cols[1].rsplit(":", 1)[1], 16)
                    state = cols[3]
                    if state == TCP_SYN_RECV:
                        half_open += 1
                        per_port_syn_recv[local_port] = per_port_syn_recv.get(local_port, 0) + 1
                    elif state == TCP_ESTABLISHED:
                        established += 1
        except (OSError, ValueError):
            continue
    return {"half_open_connections": half_open, "active_connections": established,
            "half_open_per_port": per_port_syn_recv}


def _snmp_stat(proto: str, key: str) -> int | None:
    """One counter from /proc/net/snmp (e.g. Tcp: PassiveOpens, Udp: InDatagrams)."""
    try:
        with open("/proc/net/snmp") as f:
            lines = f.read().splitlines()
    except OSError:
        return None
    header = value = None
    for i, line in enumerate(lines):
        if line.startswith(proto + ":"):
            if header is None:
                header = line.split()
            else:
                value = line.split()
                break
    if not header or not value:
        return None
    try:
        return int(value[header.index(key)])
    except (ValueError, IndexError):
        return None


def _nginx_requests() -> int | None:
    """Total handled requests from nginx stub_status, or None if unavailable."""
    try:
        import urllib.request
        with urllib.request.urlopen(NGINX_STATUS, timeout=1) as r:
            body = r.read().decode()
        # stub_status: "server accepts handled requests\n <accepts> <handled> <requests>"
        m = re.search(r"accepts handled requests\s*\n\s*(\d+)\s+(\d+)\s+(\d+)", body)
        return int(m.group(3)) if m else None
    except Exception:  # noqa: BLE001
        return None


def _listening_ports() -> list[int]:
    """TCP/UDP ports this host is listening on (from /proc/net/*)."""
    ports = set()
    for proto, state_col, want in (("tcp", 3, "0A"), ("tcp6", 3, "0A"), ("udp", 3, "07"), ("udp6", 3, "07")):
        try:
            with open("/proc/net/" + proto) as f:
                next(f)
                for line in f:
                    cols = line.split()
                    if len(cols) > state_col and cols[state_col] == want:
                        ports.add(int(cols[1].rsplit(":", 1)[1], 16))
        except (OSError, ValueError):
            continue
    return sorted(ports)


_RATE_STATE: dict[str, tuple[float, int]] = {}


def _rate(name: str, total: int | None) -> float | None:
    """Per-second rate of a monotonic counter across successive /metrics reads."""
    if total is None:
        return None
    now = time.time()
    prev = _RATE_STATE.get(name)
    _RATE_STATE[name] = (now, total)
    if prev is None or now <= prev[0]:
        return None
    return round((total - prev[1]) / (now - prev[0]), 2)


def _udp_sink_total() -> int | None:
    """Total UDP datagrams drained by the sinks (reliable even when /proc's
    InDatagrams under-counts); None if the sink is not running."""
    try:
        with open(os.environ.get("UDP_SINK_STATE", "/tmp/udp_sink.json")) as f:
            return int(json.load(f).get("total", 0))
    except (OSError, ValueError):
        return None


def snapshot() -> dict:
    tcp = _proc_tcp_counts()
    passive_opens = _snmp_stat("Tcp", "PassiveOpens")
    udp_in = _snmp_stat("Udp", "InDatagrams")
    icmp_in = _snmp_stat("Icmp", "InMsgs")
    nginx_req = _nginx_requests()
    return {
        "timestamp": time.time(),
        "hostname": socket.gethostname(),
        "half_open_connections": tcp["half_open_connections"],
        "active_connections": tcp["active_connections"],
        "half_open_per_port": tcp["half_open_per_port"],
        "listening_ports": _listening_ports(),
        "watch_ports": WATCH_PORTS,
        "rates": {
            "tcp_passive_opens_per_s": _rate("tcp_passive_opens", passive_opens),
            "udp_in_datagrams_per_s": _rate("udp_in", udp_in),
            "icmp_in_msgs_per_s": _rate("icmp_in", icmp_in),
            "http_requests_per_s": _rate("nginx_req", nginx_req),
            "udp_sink_per_s": _rate("udp_sink", _udp_sink_total()),
        },
        "totals": {
            "tcp_passive_opens": passive_opens,
            "udp_in_datagrams": udp_in,
            "icmp_in_msgs": icmp_in,
            "http_requests_handled": nginx_req,
            "udp_sink_received": _udp_sink_total(),
        },
    }


class Handler(http.server.BaseHTTPRequestHandler):
    def _send(self, code: int, payload: dict) -> None:
        body = json.dumps(payload).encode()
        self.send_response(code)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def do_GET(self) -> None:  # noqa: N802
        if self.path.rstrip("/") in ("/health",):
            self._send(200, {"status": "ok"})
        elif self.path.split("?")[0].rstrip("/") in ("", "/metrics"):
            self._send(200, snapshot())
        else:
            self._send(404, {"error": "not found"})

    def log_message(self, *args) -> None:  # keep the metrics port quiet
        pass


def main() -> None:
    port = int(os.environ.get("METRICS_PORT", "9100"))
    srv = http.server.ThreadingHTTPServer(("0.0.0.0", port), Handler)
    print(f"victim metrics on :{port}, watching ports {WATCH_PORTS}", flush=True)
    srv.serve_forever()


if __name__ == "__main__":
    main()
